### PR TITLE
Update gradle to 3.3.2 and config for internal use

### PR DESCRIPTION
**Pull request by carranca**

### CODE REVIEW

**Comment by AlecKazakova** [comment]
If we're forked already, is it possible to just go to gradle 5 - whatever cash is on?

**Comment by carranca** [comment]
> If we're forked already, is it possible to just go to gradle 5 - whatever cash is on?

Cash is still on 3.3.2

**Comment by jrodbx** [comment]
Gradle != Android Gradle Plugin

**Comment by carranca** [comment]
Re-submitting this PR internally.

**Pull request closed without merging**
